receivers:
  influxdb:
    endpoint: 0.0.0.0:8086
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus/collector:
    config:
      scrape_configs:
        - job_name: "opentelemetry-collector"
          static_configs:
            - targets: ["localhost:8888"]

processors:
  batch:
  metricstransform/hass:
    transforms:
      - include: (.*)
        match_type: regexp
        action: update
        new_name: hass.$${1}
  attributes/hass:
    actions:
      - key: service.name
        value: hass.ato.ms
        action: insert

exporters:
  otlphttp/metrics:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true
  otlphttp/traces:
    endpoint: http://tempo:4418
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
  file/archive-metrics:
    path: /file-exporter/metrics.json.zst
    rotation:
      max_megabytes: 100
      max_backups: 1000
    compression: zstd
    # XXX: currently truncates files on restart
    #append: true
  file/archive-traces:
    path: /file-exporter/traces.json.zst
    rotation:
      max_megabytes: 100
      max_backups: 20000
    compression: zstd
  file/archive-logs:
    path: /file-exporter/logs.json.zst
    rotation:
      max_megabytes: 100
      max_backups: 20000
    compression: zstd
  debug/metrics:
    verbosity: detailed
  debug/traces:
    verbosity: detailed
  debug/logs:
    verbosity: detailed

service:
  extensions: [health_check, zpages]
  pipelines:
    metrics:
      receivers: [otlp, prometheus/collector]
      processors: [batch]
      exporters: [file/archive-metrics, otlphttp/metrics]
      #exporters: [file/archive-metrics, otlphttp/metrics, debug/metrics]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/archive-traces, otlphttp/traces]
      #exporters: [otlphttp/traces,debug/traces]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/archive-logs, otlphttp/logs]
      #exporters: [otlphttp/logs,debug/logs]
    metrics/influxdebug:
      receivers: [influxdb]
      processors: [attributes/hass, metricstransform/hass, batch]
      exporters: [otlphttp/metrics]
      #exporters: [otlphttp/metrics, debug/metrics]


extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:
    endpoint: 0.0.0.0:55679
